# Site settings
name: projects
title: SHARA DUONG
author:
  name: skduong
  #email: your-email@domain.com
description: "Here is the description"

# Configs
exclude: ['./README.md']

# Build settings
remote_theme: jekyll/minima
